### ISSUE TITLE
Commands with Fish Name break if fish name has a space in it

### ISSUE THREAD

**Issue by Kunfury-blep** [Kunfury-blep/Blep-Fishing#23]
Example:
Red Grouper
Red-Bellied Piranha

Brought up be PeeKayy on discord

**Comment by PeeeKayy** [comment]
Currently i only found /bf spawn fish commands having this problem. 
I'm also not certain the tournaments in tournaments.yml that have these fishes works.

other fishes are: Pink salmon, Brown Trout, Electric Eel, Armored Catfish

**Comment by Kunfury-blep** [comment]
Fixed, now uses quotation marks to support spaces
