### ISSUE TITLE
[Feature Request] Type ALL on Leaderboard Signs

### ISSUE THREAD

**Issue by ZandercraftGames** [Kunfury-blep/Blep-Fishing#4]
It would be really useful to have a type "ALL" for leaderboard signs just like with the fishing tourneys. That way we can list the top person overall and what fish they caught.

**Comment by Kunfury-blep** [comment]
Resolved! Introduced a fix in the latest update, this also made me go back and lookover the code for signs which was.... extremely messy. It's still a mess but has been improved slightly. 
Thanks for the suggestion!

**Comment by ZandercraftGames** [comment]
> Resolved! Introduced a fix in the latest update, this also made me go back and lookover the code for signs which was.... extremely messy. It's still a mess but has been improved slightly. 
> Thanks for the suggestion! 

Thanks for implementing it! I really appreciate it!
