### ISSUE TITLE
allow fish to be caught in multiple areas

### ISSUE THREAD

**Issue by gremlinwithsandals** [Kunfury-blep/Blep-Fishing#6]
Instead of requiring a new area to be created containing both of the original area's biomes, we should just be able to input both original areas and get the same result.

**Comment by Kunfury-blep** [comment]
I know it has been an extremely long time but I am actively working on adding this to the plugin now! Thank you so much for your suggestion!

**Comment by Kunfury-blep** [comment]
Implemented, will be included in the next update
