### ISSUE TITLE
Attempted to run admin command.

### ISSUE THREAD

**Issue by Antmanofgod** [Kunfury-blep/Blep-Fishing#8]
While trying to run the admin command, I got this error:

`
28.09 19:29:24 [Server] WARN Unexpected exception while parsing console command "bf admin"
28.09 19:29:24 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'bf' in plugin BlepFishing v1.7.5
28.09 19:29:24 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-280]
28.09 19:29:24 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.09 19:29:24 [Server] INFO Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
28.09 19:29:24 [Server] INFO at com.kunfury.blepFishing.Admin.AdminMenu.ShowInventory(AdminMenu.java:52) ~[Blep Fishing-1.7.5.jar:?]
28.09 19:29:24 [Server] INFO at com.kunfury.blepFishing.Commands.SubCommands.AdminSubcommand.perform(AdminSubcommand.java:31) ~[Blep Fishing-1.7.5.jar:?]
28.09 19:29:24 [Server] INFO at com.kunfury.blepFishing.Commands.CommandManager.onCommand(CommandManager.java:40) ~[Blep Fishing-1.7.5.jar:?]
28.09 19:29:24 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-280]
`

**Comment by Kunfury-blep** [comment]
Could you please tell me what the solution was so that I can help others in the future if these errors pop up again?
